---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-password
  namespace: poc
spec:
  encryptedData:
    password: AgCmh4aT2K7jze/U3NrfzuM5YBMAJTThbQ+CX49s/IrMNkmhDKhlILsVQm5tjODkE2hfQIsJe1d0qyFsy4VY4GbHq69GTCx02wmMa3/8Y2UcAPEHqUVQD87PtdUtQ0sBVd8lM9fqohy1LJkggU6FzxOUSEz0zYwOWwvPWqG46JnkPHF8KgpsU/I6Gfrpa0o2edPNu4Jl+F5SVytK6ZeZcrr27zDXqqGrR0vgwe3lY5BZOfqRiOy0sw2c9uQxZtZ9QHNq8v8rpkZf0h11AB9bw2a8Nu6+5953xENVWg/D3roE3DCBnj7ZdwrvVjdk035vi4EXg6KN/ATigk5lB/7wnJwCwocpgO+vH3/3FIacUY3JNNVU0/lHC5Q+GEzLG/KI8tgnDfJAgXRwAmioI0Roi6rW4+4H+adbxuuiAOQOBsSc7wPibOZHoF3T4o61H2l5EQlzly6snqv7EomcfZbCw/vOmWWe1bksJMQBwx8HRqxjmnIGUb9xkOnzeS0ML1X/Jn01jHvWKe27Dl/aPPwfWYhp+6uAhzKa36hLIGTrRorYdla3nn5u2EuFO5lDAHIww8vfIPrQxmCWFnIaCY0cuOnB2GdXTrSl/QqrGsekNCYdMUjguT1cZqGJAsg9Xwa+2isrGf0+DWtQ6MUjH4I8C841ba+kdPaDPVz1ocCFH4RlabDbZfWGgAkyfzxQ3fvudd/ld9NoIyFNOg==
  template:
    metadata:
      creationTimestamp: null
      name: db-password
      namespace: poc
    type: Opaque
