apiVersion: v1
kind: Service
metadata:
  name: aspnet
  namespace: poc
spec:
  type: ClusterIP
  selector:
    app: aspnet-app-green
    deployment: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80