apiVersion: v1
kind: Service
metadata:
  name: aspnet
  namespace: poc
spec:
  type: ClusterIP
  selector:
    app: aspnet-app
    deployment: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80