apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnet-app-green
  namespace: poc
spec:
  selector:
    matchLabels:
      app: aspnet-app-green
      deployment: green
  replicas: 1
  template:
    metadata:
      labels:
        app: aspnet-app-green
        deployment: green
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - aspnet-app-green
              - key: deployment
                operator: In
                values:
                - green
            topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - pool1
      containers:
        - name: aspnet-app
          image: "pocacr2024.azurecr.io/application:v2"
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:80"
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: mysql-connection-string
                  key: password
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
