kind: Secret
apiVersion: v1
metadata:
  name: mysql-connection-string
  namespace: poc
data:
  password: >-
    c2VydmVyPW15c3FsO3VzZXI9cm9vdDtkYXRhYmFzZT1teXNxbDtwb3J0PTMzMDY7cGFzc3dvcmQ9ZGItcTVuMmc=
type: Opaque
